# 数据源配置 
spring:
    h2:
      console:
        #表示可以在浏览器中访问H2的控制台
        #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
        enabled: true
        #进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
        settings:
          web-allow-others: true
        #进行该配置，你就可以通过YOUR_URL/h2-console访问h2 web consloe。YOUR_URL是你程序的访问URl。
        path: /h2-console
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        # driverClassName: com.mysql.cj.jdbc.Driver
        driver-class-name: org.h2.Driver
        druid:
            # 主库数据源
            master:
               # url: jdbc:mysql://localhost:3306/ry_20190822?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
               # username: root
               # password: root
                 url: jdbc:h2:file:D:\172.1.3.40_SVN\01-质量管理\ZFXM9999999调度程序\05程序\01-SRC\RuoYi-fast\data\flow;FILE_LOCK=SOCKET;MODE=MYSQL;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;MVCC=TRUE
                 username: sa
                 password: sa
                 #启动时需要初始化的建表语句
                 #schema: classpath:sql/quartz.sql
                 #初始化的数据
                 #data: classpath:sql/ry_20190822.sql
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: 
                login-password: 
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true