-- AL.FLOW_INFO definition

-- Drop table

-- DROP TABLE AL.FLOW_INFO;

CREATE TABLE AL.FLOW_INFO (
  FLOW_ID VARCHAR(64) NOT NULL,
  FLOW_NAME VARCHAR(256) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100)
);


-- AL.FLOW_JDBC_SET definition

-- Drop table

-- DROP TABLE AL.FLOW_JDBC_SET;

CREATE TABLE AL.FLOW_JDBC_SET (
  ID VARCHAR(256) NOT NULL,
  JDBC_NAME VARCHAR(256) NOT NULL,
  JDBC_DRIVER VARCHAR(256) NOT NULL,
  JDBC_URL VARCHAR(256) NOT NULL,
  JDBC_USERNAME VARCHAR(256) NOT NULL,
  JDBC_PASSWORD VARCHAR(256) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100)
);


-- AL.FLOW_LOG definition

-- Drop table

-- DROP TABLE AL.FLOW_LOG;

CREATE TABLE AL.FLOW_LOG (
  ID VARCHAR(100),
  FLOW_SL_ID VARCHAR(100),
  FLOW_NAME VARCHAR(500),
  START_TIME VARCHAR(100),
  END_TIME VARCHAR(100),
  STAUTS VARCHAR(100),
  PARAM VARCHAR(2000),
  CREATE_BY VARCHAR(100),
  CREATE_TIME VARCHAR(100),
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(3000)
);


-- AL.FLOW_LOG_DETAIL definition

-- Drop table

-- DROP TABLE AL.FLOW_LOG_DETAIL;

CREATE TABLE AL.FLOW_LOG_DETAIL (
  ID VARCHAR(500),
  FLOW_SL_ID VARCHAR(100),
  FLOW_NAME VARCHAR(500),
  FLOW_NODE_ID VARCHAR(100),
  FLOW_NODE_NAME VARCHAR(500),
  START_TIME VARCHAR(100),
  END_TIME VARCHAR(100),
  STAUTS VARCHAR(100),
  CREATE_BY VARCHAR(100),
  CREATE_TIME VARCHAR(100),
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(3000)
);


-- AL.FLOW_PARAM_INFO definition

-- Drop table

-- DROP TABLE AL.FLOW_PARAM_INFO;

CREATE TABLE AL.FLOW_PARAM_INFO (
  FLOW_ID VARCHAR(64) NOT NULL,
  PARAM_KEY VARCHAR(100) NOT NULL,
  PARAM_VALUE VARCHAR(100) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100),
  ID VARCHAR(100)
);


-- AL.FLOW_SSH_SET definition

-- Drop table

-- DROP TABLE AL.FLOW_SSH_SET;

CREATE TABLE AL.FLOW_SSH_SET (
  ID VARCHAR(256) NOT NULL,
  SSH_NAME VARCHAR(256) NOT NULL,
  SSH_HOSTNAME VARCHAR(256) NOT NULL,
  SSH_USERNAME VARCHAR(256) NOT NULL,
  SSH_PASSWORD VARCHAR(256) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100)
);


-- AL.FLOW_TASK_AREA definition

-- Drop table

-- DROP TABLE AL.FLOW_TASK_AREA;

CREATE TABLE AL.FLOW_TASK_AREA (
  FLOWID VARCHAR(64) NOT NULL,
  ID VARCHAR(256) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  "LEFT" VARCHAR(256) NOT NULL,
  "TOP" VARCHAR(256) NOT NULL,
  COLOR VARCHAR(256) NOT NULL,
  WIDTH VARCHAR(256) NOT NULL,
  HEIGHT VARCHAR(256) NOT NULL,
  ALT VARCHAR(256) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100)
);


-- AL.FLOW_TASK_INFO definition

-- Drop table

-- DROP TABLE AL.FLOW_TASK_INFO;

CREATE TABLE AL.FLOW_TASK_INFO (
  FLOW_ID VARCHAR(64) NOT NULL,
  INITNUM VARCHAR(64) NOT NULL,
  FLOW_JSON_0 VARCHAR(3000) NOT NULL,
  FLOW_JSON_1 VARCHAR(3000) NOT NULL,
  FLOW_JSON_2 VARCHAR(3000) NOT NULL,
  FLOW_JSON_3 VARCHAR(3000) NOT NULL,
  FLOW_JSON_4 VARCHAR(3000) NOT NULL,
  FLOW_JSON_5 VARCHAR(3000) NOT NULL,
  FLOW_JSON_6 VARCHAR(3000) NOT NULL,
  FLOW_JSON_7 VARCHAR(3000) NOT NULL,
  FLOW_JSON_8 VARCHAR(3000) NOT NULL,
  FLOW_JSON_9 VARCHAR(3000) NOT NULL,
  FLOW_JSON_10 VARCHAR(3000) NOT NULL,
  FLOW_JSON_11 VARCHAR(3000) NOT NULL,
  FLOW_JSON_12 VARCHAR(3000) NOT NULL,
  FLOW_JSON_13 VARCHAR(3000) NOT NULL,
  FLOW_JSON_14 VARCHAR(3000) NOT NULL,
  FLOW_JSON_15 VARCHAR(3000) NOT NULL,
  FLOW_JSON_16 VARCHAR(3000) NOT NULL,
  FLOW_JSON_17 VARCHAR(3000) NOT NULL,
  FLOW_JSON_18 VARCHAR(3000) NOT NULL,
  FLOW_JSON_19 VARCHAR(3000) NOT NULL,
  FLOW_JSON_20 VARCHAR(3000) NOT NULL,
  FLOW_JSON_21 VARCHAR(3000) NOT NULL,
  FLOW_JSON_22 VARCHAR(3000) NOT NULL,
  FLOW_JSON_23 VARCHAR(3000) NOT NULL,
  FLOW_JSON_24 VARCHAR(3000) NOT NULL,
  FLOW_JSON_25 VARCHAR(3000) NOT NULL,
  FLOW_JSON_26 VARCHAR(3000) NOT NULL,
  FLOW_JSON_27 VARCHAR(3000) NOT NULL,
  FLOW_JSON_28 VARCHAR(3000) NOT NULL,
  FLOW_JSON_29 VARCHAR(3000) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100)
);


-- AL.FLOW_TASK_LINE definition

-- Drop table

-- DROP TABLE AL.FLOW_TASK_LINE;

CREATE TABLE AL.FLOW_TASK_LINE (
  FLOWID VARCHAR(64) NOT NULL,
  ID VARCHAR(256) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  C_TYPE VARCHAR(256) NOT NULL,
  C_FROM VARCHAR(256) NOT NULL,
  C_TO VARCHAR(256) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100)
);


-- AL.FLOW_TASK_NODE definition

-- Drop table

-- DROP TABLE AL.FLOW_TASK_NODE;

CREATE TABLE AL.FLOW_TASK_NODE (
  FLOWID VARCHAR(64) NOT NULL,
  ID VARCHAR(256) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  "LEFT" VARCHAR(256) NOT NULL,
  "TOP" VARCHAR(256) NOT NULL,
  "TYPE" VARCHAR(256) NOT NULL,
  WIDTH VARCHAR(256) NOT NULL,
  HEIGHT VARCHAR(256) NOT NULL,
  ALT VARCHAR(256) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100)
);


-- AL.FLOW_TASK_SUB_INFO definition

-- Drop table

-- DROP TABLE AL.FLOW_TASK_SUB_INFO;

CREATE TABLE AL.FLOW_TASK_SUB_INFO (
  FLOW_ID VARCHAR(64) NOT NULL,
  SUB_TASK_ID VARCHAR(64) NOT NULL,
  SUB_TASK_NAME VARCHAR(512) NOT NULL,
  SUB_TASK_TYPE VARCHAR(128) NOT NULL,
  SUB_TASK_MODEL VARCHAR(128) NOT NULL,
  SUB_TASK_JDBC_ID VARCHAR(128) NOT NULL,
  SUB_TASK_SSH_ID VARCHAR(128) NOT NULL,
  SUB_TASK_LEFT_R VARCHAR(128) NOT NULL,
  SUB_TASK_TOP_R VARCHAR(128) NOT NULL,
  SUB_TASK_WIDTH VARCHAR(128) NOT NULL,
  SUB_TASK_HEIGHT VARCHAR(128) NOT NULL,
  SUB_TASK_FROM VARCHAR(128) NOT NULL,
  SUB_TASK_TO VARCHAR(128) NOT NULL,
  EXE_STR_0 VARCHAR(3000) NOT NULL,
  EXE_STR_1 VARCHAR(3000) NOT NULL,
  EXE_STR_2 VARCHAR(3000) NOT NULL,
  EXE_STR_3 VARCHAR(3000) NOT NULL,
  EXE_STR_4 VARCHAR(3000) NOT NULL,
  EXE_STR_5 VARCHAR(3000) NOT NULL,
  EXE_STR_6 VARCHAR(3000) NOT NULL,
  EXE_STR_7 VARCHAR(3000) NOT NULL,
  EXE_STR_8 VARCHAR(3000) NOT NULL,
  EXE_STR_9 VARCHAR(3000) NOT NULL,
  EXE_STR_10 VARCHAR(3000) NOT NULL,
  EXE_STR_11 VARCHAR(3000) NOT NULL,
  EXE_STR_12 VARCHAR(3000) NOT NULL,
  EXE_STR_13 VARCHAR(3000) NOT NULL,
  EXE_STR_14 VARCHAR(3000) NOT NULL,
  EXE_STR_15 VARCHAR(3000) NOT NULL,
  EXE_STR_16 VARCHAR(3000) NOT NULL,
  EXE_STR_17 VARCHAR(3000) NOT NULL,
  EXE_STR_18 VARCHAR(3000) NOT NULL,
  EXE_STR_19 VARCHAR(3000) NOT NULL,
  CREATE_BY VARCHAR(100) NOT NULL,
  CREATE_TIME VARCHAR(100) NOT NULL,
  UPDATE_BY VARCHAR(100),
  UPDATE_TIME VARCHAR(100),
  REMARK VARCHAR(100)
);


-- AL.GEN_TABLE definition

-- Drop table

-- DROP TABLE AL.GEN_TABLE;

CREATE TABLE AL.GEN_TABLE (
  TABLE_ID VARCHAR(200)  ,
  TABLE_NAME VARCHAR(200) DEFAULT '',
  TABLE_COMMENT VARCHAR(500) DEFAULT '',
  CLASS_NAME VARCHAR(100) DEFAULT '',
  TPL_CATEGORY VARCHAR(200) DEFAULT 'crud',
  PACKAGE_NAME VARCHAR(100),
  MODULE_NAME VARCHAR(30),
  BUSINESS_NAME VARCHAR(30),
  FUNCTION_NAME VARCHAR(50),
  FUNCTION_AUTHOR VARCHAR(50),
  "OPTIONS" VARCHAR(1000),
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT NULL,
  CONSTRAINT CONSTRAINT_E3 PRIMARY KEY (TABLE_ID)
); 


-- AL.GEN_TABLE_COLUMN definition

-- Drop table

-- DROP TABLE AL.GEN_TABLE_COLUMN;

CREATE TABLE AL.GEN_TABLE_COLUMN (
  COLUMN_ID VARCHAR(200)  ,
  TABLE_ID VARCHAR(64),
  COLUMN_NAME VARCHAR(200),
  COLUMN_COMMENT VARCHAR(500),
  COLUMN_TYPE VARCHAR(100),
  JAVA_TYPE VARCHAR(500),
  JAVA_FIELD VARCHAR(200),
  IS_PK CHAR(1),
  IS_INCREMENT CHAR(1),
  IS_REQUIRED CHAR(1),
  IS_INSERT CHAR(1),
  IS_EDIT CHAR(1),
  IS_LIST CHAR(1),
  IS_QUERY CHAR(1),
  QUERY_TYPE VARCHAR(200) DEFAULT 'EQ',
  HTML_TYPE VARCHAR(200),
  DICT_TYPE VARCHAR(200) DEFAULT '',
  SORT INTEGER,
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  CONSTRAINT CONSTRAINT_87 PRIMARY KEY (COLUMN_ID)
); 


-- AL.QRTZ_CALENDARS definition

-- Drop table

-- DROP TABLE AL.QRTZ_CALENDARS;

CREATE TABLE AL.QRTZ_CALENDARS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  CALENDAR_NAME VARCHAR(200) NOT NULL,
  CALENDAR varchar2(4000) NOT NULL,
  CONSTRAINT CONSTRAINT_BF PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
); 


-- AL.QRTZ_FIRED_TRIGGERS definition

-- Drop table

-- DROP TABLE AL.QRTZ_FIRED_TRIGGERS;

CREATE TABLE AL.QRTZ_FIRED_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  ENTRY_ID VARCHAR(95) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  FIRED_TIME VARCHAR(200)  NOT NULL,
  SCHED_TIME VARCHAR(200)  NOT NULL,
  PRIORITY INTEGER NOT NULL,
  STATE VARCHAR(200) NOT NULL,
  JOB_NAME VARCHAR(200),
  JOB_GROUP VARCHAR(200),
  IS_NONCONCURRENT VARCHAR(200),
  REQUESTS_RECOVERY VARCHAR(200),
  CONSTRAINT CONSTRAINT_F PRIMARY KEY (SCHED_NAME,ENTRY_ID)
); 


-- AL.QRTZ_JOB_DETAILS definition

-- Drop table

-- DROP TABLE AL.QRTZ_JOB_DETAILS;

CREATE TABLE AL.QRTZ_JOB_DETAILS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  JOB_NAME VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250),
  JOB_CLASS_NAME VARCHAR(250) NOT NULL,
  IS_DURABLE VARCHAR(250) NOT NULL,
  IS_NONCONCURRENT VARCHAR(250) NOT NULL,
  IS_UPDATE_DATA VARCHAR(250) NOT NULL,
  REQUESTS_RECOVERY VARCHAR(250) NOT NULL,
  JOB_DATA varchar2(4000),
  CONSTRAINT CONSTRAINT_B PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
); 


-- AL.QRTZ_LOCKS definition

-- Drop table

-- DROP TABLE AL.QRTZ_LOCKS;

CREATE TABLE AL.QRTZ_LOCKS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  LOCK_NAME VARCHAR(40) NOT NULL,
  CONSTRAINT CONSTRAINT_1 PRIMARY KEY (SCHED_NAME,LOCK_NAME)
); 

-- AL.QRTZ_PAUSED_TRIGGER_GRPS definition

-- Drop table

-- DROP TABLE AL.QRTZ_PAUSED_TRIGGER_GRPS;

CREATE TABLE AL.QRTZ_PAUSED_TRIGGER_GRPS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  CONSTRAINT CONSTRAINT_7 PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
); 


-- AL.QRTZ_SCHEDULER_STATE definition

-- Drop table

-- DROP TABLE AL.QRTZ_SCHEDULER_STATE;

CREATE TABLE AL.QRTZ_SCHEDULER_STATE (
  SCHED_NAME VARCHAR(120) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  LAST_CHECKIN_TIME VARCHAR(200)  NOT NULL,
  CHECKIN_INTERVAL VARCHAR(200)  NOT NULL,
  CONSTRAINT CONSTRAINT_6 PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
); 


-- AL.SYS_CONFIG definition

-- Drop table

-- DROP TABLE AL.SYS_CONFIG;

CREATE TABLE AL.SYS_CONFIG (
  CONFIG_ID INTEGER ,
  CONFIG_NAME VARCHAR(100) DEFAULT '',
  CONFIG_KEY VARCHAR(100) DEFAULT '',
  CONFIG_VALUE VARCHAR(500) DEFAULT '',
  CONFIG_TYPE CHAR(1) DEFAULT 'N',
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT NULL,
  CONSTRAINT CONSTRAINT_85 PRIMARY KEY (CONFIG_ID)
); 


-- AL.SYS_DEPT definition

-- Drop table

-- DROP TABLE AL.SYS_DEPT;

CREATE TABLE AL.SYS_DEPT (
  DEPT_ID VARCHAR(200)  ,
  PARENT_ID VARCHAR(200)  DEFAULT 0,
  ANCESTORS VARCHAR(50) DEFAULT '',
  DEPT_NAME VARCHAR(30) DEFAULT '',
  ORDER_NUM INTEGER DEFAULT 0,
  LEADER VARCHAR(20) DEFAULT NULL,
  PHONE VARCHAR(11) DEFAULT NULL,
  EMAIL VARCHAR(50) DEFAULT NULL,
  STATUS CHAR(1) DEFAULT '0',
  DEL_FLAG CHAR(1) DEFAULT '0',
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  CONSTRAINT CONSTRAINT_A PRIMARY KEY (DEPT_ID)
); 


-- AL.SYS_DICT_DATA definition

-- Drop table

-- DROP TABLE AL.SYS_DICT_DATA;

CREATE TABLE AL.SYS_DICT_DATA (
  DICT_CODE VARCHAR(200)  ,
  DICT_SORT INTEGER DEFAULT 0,
  DICT_LABEL VARCHAR(100) DEFAULT '',
  DICT_VALUE VARCHAR(100) DEFAULT '',
  DICT_TYPE VARCHAR(100) DEFAULT '',
  CSS_CLASS VARCHAR(100) DEFAULT NULL,
  LIST_CLASS VARCHAR(100) DEFAULT NULL,
  IS_DEFAULT CHAR(1) DEFAULT 'N',
  STATUS CHAR(1) DEFAULT '0',
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT NULL,
  CONSTRAINT CONSTRAINT_5C PRIMARY KEY (DICT_CODE)
); 


-- AL.SYS_DICT_TYPE definition

-- Drop table

-- DROP TABLE AL.SYS_DICT_TYPE;

CREATE TABLE AL.SYS_DICT_TYPE (
  DICT_ID VARCHAR(200)  ,
  DICT_NAME VARCHAR(100) DEFAULT '',
  DICT_TYPE VARCHAR(100) DEFAULT '',
  STATUS CHAR(1) DEFAULT '0',
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT NULL,
  CONSTRAINT CONSTRAINT_5 PRIMARY KEY (DICT_ID)
); 


-- AL.SYS_JOB definition

-- Drop table

-- DROP TABLE AL.SYS_JOB;

CREATE TABLE AL.SYS_JOB (
  JOB_ID VARCHAR(200)  ,
  JOB_NAME VARCHAR(64) DEFAULT '' NOT NULL,
  JOB_GROUP VARCHAR(64) DEFAULT 'DEFAULT' NOT NULL,
  INVOKE_TARGET VARCHAR(500) NOT NULL,
  CRON_EXPRESSION VARCHAR(255) DEFAULT '',
  MISFIRE_POLICY VARCHAR(20) DEFAULT '3',
  CONCURRENT CHAR(1) DEFAULT '1',
  STATUS CHAR(1) DEFAULT '0',
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT '',
  CONSTRAINT CONSTRAINT_C PRIMARY KEY (JOB_ID,JOB_NAME,JOB_GROUP)
); 


-- AL.SYS_JOB_LOG definition

-- Drop table

-- DROP TABLE AL.SYS_JOB_LOG;

CREATE TABLE AL.SYS_JOB_LOG (
  JOB_LOG_ID VARCHAR(200)  ,
  JOB_NAME VARCHAR(64) NOT NULL,
  JOB_GROUP VARCHAR(64) NOT NULL,
  INVOKE_TARGET VARCHAR(500) NOT NULL,
  JOB_MESSAGE VARCHAR(500),
  STATUS CHAR(1) DEFAULT '0',
  EXCEPTION_INFO VARCHAR(2000) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  CONSTRAINT CONSTRAINT_A7 PRIMARY KEY (JOB_LOG_ID)
); 


-- AL.SYS_LOGININFOR definition

-- Drop table

-- DROP TABLE AL.SYS_LOGININFOR;

CREATE TABLE AL.SYS_LOGININFOR (
  INFO_ID VARCHAR(200)  ,
  LOGIN_NAME VARCHAR(50) DEFAULT '',
  IPADDR VARCHAR(50) DEFAULT '',
  LOGIN_LOCATION VARCHAR(255) DEFAULT '',
  BROWSER VARCHAR(50) DEFAULT '',
  OS VARCHAR(50) DEFAULT '',
  STATUS CHAR(1) DEFAULT '0',
  MSG VARCHAR(255) DEFAULT '',
  LOGIN_TIME TIMESTAMP,
  CONSTRAINT CONSTRAINT_9 PRIMARY KEY (INFO_ID)
); 

-- AL.SYS_MENU definition

-- Drop table

-- DROP TABLE AL.SYS_MENU;

CREATE TABLE AL.SYS_MENU (
  MENU_ID VARCHAR(200)  ,
  MENU_NAME VARCHAR(50) NOT NULL,
  PARENT_ID VARCHAR(200)  DEFAULT 0,
  ORDER_NUM INTEGER DEFAULT 0,
  URL VARCHAR(200) DEFAULT '#',
  TARGET VARCHAR(20) DEFAULT '',
  MENU_TYPE CHAR(1) DEFAULT '',
  VISIBLE CHAR(1) DEFAULT 0,
  PERMS VARCHAR(100) DEFAULT NULL,
  ICON VARCHAR(100) DEFAULT '#',
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT '',
  CONSTRAINT CONSTRAINT_A50D PRIMARY KEY (MENU_ID)
); 

-- AL.SYS_NOTICE definition

-- Drop table

-- DROP TABLE AL.SYS_NOTICE;

CREATE TABLE AL.SYS_NOTICE (
  NOTICE_ID INTEGER ,
  NOTICE_TITLE VARCHAR(50) NOT NULL,
  NOTICE_TYPE CHAR(1) NOT NULL,
  NOTICE_CONTENT VARCHAR(2000) DEFAULT NULL,
  STATUS CHAR(1) DEFAULT '0',
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(255) DEFAULT NULL,
  CONSTRAINT CONSTRAINT_98 PRIMARY KEY (NOTICE_ID)
); 

-- AL.SYS_OPER_LOG definition

-- Drop table

-- DROP TABLE AL.SYS_OPER_LOG;

CREATE TABLE AL.SYS_OPER_LOG (
  OPER_ID VARCHAR(200)  ,
  TITLE VARCHAR(50) DEFAULT '',
  BUSINESS_TYPE INTEGER DEFAULT 0,
  "METHOD" VARCHAR(100) DEFAULT '',
  REQUEST_METHOD VARCHAR(10) DEFAULT '',
  OPERATOR_TYPE INTEGER DEFAULT 0,
  OPER_NAME VARCHAR(50) DEFAULT '',
  DEPT_NAME VARCHAR(50) DEFAULT '',
  OPER_URL VARCHAR(255) DEFAULT '',
  OPER_IP VARCHAR(50) DEFAULT '',
  OPER_LOCATION VARCHAR(255) DEFAULT '',
  OPER_PARAM VARCHAR(2000) DEFAULT '',
  STATUS INTEGER DEFAULT 0,
  ERROR_MSG VARCHAR(2000) DEFAULT '',
  OPER_TIME TIMESTAMP,
  CONSTRAINT CONSTRAINT_8 PRIMARY KEY (OPER_ID)
); 


-- AL.SYS_POST definition

-- Drop table

-- DROP TABLE AL.SYS_POST;

CREATE TABLE AL.SYS_POST (
  POST_ID VARCHAR(200)  ,
  POST_CODE VARCHAR(64) NOT NULL,
  POST_NAME VARCHAR(50) NOT NULL,
  POST_SORT INTEGER NOT NULL,
  STATUS CHAR(1) NOT NULL,
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT NULL,
  CONSTRAINT CONSTRAINT_A50 PRIMARY KEY (POST_ID)
); 

-- AL.SYS_ROLE definition

-- Drop table

-- DROP TABLE AL.SYS_ROLE;

CREATE TABLE AL.SYS_ROLE (
  ROLE_ID VARCHAR(200)  ,
  ROLE_NAME VARCHAR(30) NOT NULL,
  ROLE_KEY VARCHAR(100) NOT NULL,
  ROLE_SORT INTEGER NOT NULL,
  DATA_SCOPE CHAR(1) DEFAULT '1',
  STATUS CHAR(1) NOT NULL,
  DEL_FLAG CHAR(1) DEFAULT '0',
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT NULL,
  CONSTRAINT CONSTRAINT_A50F PRIMARY KEY (ROLE_ID)
); 

-- AL.SYS_ROLE_DEPT definition

-- Drop table

-- DROP TABLE AL.SYS_ROLE_DEPT;

CREATE TABLE AL.SYS_ROLE_DEPT (
  ROLE_ID VARCHAR(200)  NOT NULL,
  DEPT_ID VARCHAR(200)  NOT NULL,
  CONSTRAINT CONSTRAINT_AA7 PRIMARY KEY (ROLE_ID,DEPT_ID)
); 

-- AL.SYS_ROLE_MENU definition

-- Drop table

-- DROP TABLE AL.SYS_ROLE_MENU;

CREATE TABLE AL.SYS_ROLE_MENU (
  ROLE_ID VARCHAR(200)  NOT NULL,
  MENU_ID VARCHAR(200)  NOT NULL,
  CONSTRAINT CONSTRAINT_AA8 PRIMARY KEY (ROLE_ID,MENU_ID)
); 

-- AL.SYS_USER definition

-- Drop table

-- DROP TABLE AL.SYS_USER;

CREATE TABLE AL.SYS_USER (
  USER_ID VARCHAR(200) ,
  DEPT_ID VARCHAR(200)  DEFAULT NULL,
  LOGIN_NAME VARCHAR(30) NOT NULL,
  USER_NAME VARCHAR(30) NOT NULL,
  USER_TYPE VARCHAR(2) DEFAULT '00',
  EMAIL VARCHAR(50) DEFAULT '',
  PHONENUMBER VARCHAR(11) DEFAULT '',
  SEX CHAR(1) DEFAULT '0',
  AVATAR VARCHAR(100) DEFAULT '',
  PASSWORD VARCHAR(50) DEFAULT '',
  SALT VARCHAR(20) DEFAULT '',
  STATUS CHAR(1) DEFAULT '0',
  DEL_FLAG CHAR(1) DEFAULT '0',
  LOGIN_IP VARCHAR(50) DEFAULT '',
  LOGIN_DATE TIMESTAMP,
  CREATE_BY VARCHAR(64) DEFAULT '',
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR(64) DEFAULT '',
  UPDATE_TIME TIMESTAMP,
  REMARK VARCHAR(500) DEFAULT NULL,
  CONSTRAINT CONSTRAINT_A5 PRIMARY KEY (USER_ID)
); 

-- AL.SYS_USER_ONLINE definition

-- Drop table

-- DROP TABLE AL.SYS_USER_ONLINE;

CREATE TABLE AL.SYS_USER_ONLINE (
  SESSIONID VARCHAR(50) DEFAULT '' NOT NULL,
  LOGIN_NAME VARCHAR(50) DEFAULT '',
  DEPT_NAME VARCHAR(50) DEFAULT '',
  IPADDR VARCHAR(50) DEFAULT '',
  LOGIN_LOCATION VARCHAR(255) DEFAULT '',
  BROWSER VARCHAR(50) DEFAULT '',
  OS VARCHAR(50) DEFAULT '',
  STATUS VARCHAR(10) DEFAULT '',
  START_TIMESTAMP TIMESTAMP,
  LAST_ACCESS_TIME TIMESTAMP,
  EXPIRE_TIME INTEGER DEFAULT 0,
  CONSTRAINT CONSTRAINT_E PRIMARY KEY (SESSIONID)
); 

-- AL.SYS_USER_POST definition

-- Drop table

-- DROP TABLE AL.SYS_USER_POST;

CREATE TABLE AL.SYS_USER_POST (
  USER_ID VARCHAR(200)  NOT NULL,
  POST_ID VARCHAR(200)  NOT NULL,
  CONSTRAINT CONSTRAINT_AAB PRIMARY KEY (USER_ID,POST_ID)
); 
-- AL.SYS_USER_ROLE definition

-- Drop table

-- DROP TABLE AL.SYS_USER_ROLE;

CREATE TABLE AL.SYS_USER_ROLE (
  USER_ID VARCHAR(200)  NOT NULL,
  ROLE_ID VARCHAR(200)  NOT NULL,
  CONSTRAINT CONSTRAINT_AA PRIMARY KEY (USER_ID,ROLE_ID)
); 

-- AL.QRTZ_TRIGGERS definition

-- Drop table

-- DROP TABLE AL.QRTZ_TRIGGERS;

CREATE TABLE AL.QRTZ_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  JOB_NAME VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250),
  NEXT_FIRE_TIME VARCHAR(200) ,
  PREV_FIRE_TIME VARCHAR(200) ,
  PRIORITY INTEGER,
  TRIGGER_STATE VARCHAR(200) NOT NULL,
  TRIGGER_TYPE VARCHAR(200) NOT NULL,
  START_TIME VARCHAR(200)  NOT NULL,
  END_TIME VARCHAR(200) ,
  CALENDAR_NAME VARCHAR(200),
  MISFIRE_INSTR SMALLINT,
  JOB_DATA varchar2(4000)
);  

-- AL.QRTZ_varchar2(4000)_TRIGGERS definition

-- Drop table

-- DROP TABLE AL.QRTZ_varchar2(4000)_TRIGGERS;

CREATE TABLE AL.QRTZ_BIGINT_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  BIGINT_DATA varchar2(4000)
); 

-- AL.QRTZ_CRON_TRIGGERS definition

-- Drop table

-- DROP TABLE AL.QRTZ_CRON_TRIGGERS;

CREATE TABLE AL.QRTZ_CRON_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  CRON_EXPRESSION VARCHAR(200) NOT NULL,
  TIME_ZONE_ID VARCHAR(80)
); 

-- AL.QRTZ_SIMPLE_TRIGGERS definition

-- Drop table

-- DROP TABLE AL.QRTZ_SIMPLE_TRIGGERS;

CREATE TABLE AL.QRTZ_SIMPLE_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  REPEAT_COUNT VARCHAR(200)  NOT NULL,
  REPEAT_INTERVAL VARCHAR(200)  NOT NULL,
  TIMES_TRIGGERED VARCHAR(200)  NOT NULL
); 

-- AL.QRTZ_SIMPROP_TRIGGERS definition

-- Drop table

-- DROP TABLE AL.QRTZ_SIMPROP_TRIGGERS;

CREATE TABLE AL.QRTZ_SIMPROP_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  STR_PROP_1 VARCHAR(512),
  STR_PROP_2 VARCHAR(512),
  STR_PROP_3 VARCHAR(512),
  INT_PROP_1 INTEGER,
  INT_PROP_2 INTEGER,
  LONG_PROP_1 VARCHAR(200) ,
  LONG_PROP_2 VARCHAR(200) ,
  DEC_PROP_1 DECIMAL(13,4),
  DEC_PROP_2 DECIMAL(13,4),
  BOOL_PROP_1 VARCHAR(200),
  BOOL_PROP_2 VARCHAR(200)
); 